using Tyuiu.SadykovSV.Sprint1.Task3.V9.Lib;
DataService ds = new DataService();
Console.Title = "Спринт #1 | Выполнил: Садыков С.В. | ПИНБ-26-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #1                                                               *");
Console.WriteLine("* Тема: Операторы составного присваивания                                 *");
Console.WriteLine("* Задание #3                                                              *");
Console.WriteLine("* Вариант #9                                                              *");
Console.WriteLine("* Выполнил: Садыков С.В. | ПИНБ-26-1                                      *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                *");
Console.WriteLine("* Написать программу пересчета величины временного интервала,             *");
Console.WriteLine("* заданного в минутах, в величину, выраженную в часах и минутах.          *");
Console.WriteLine("*                                                                         *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Исходные данные:                                                        *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Введите временной интервал (в минутах)                                  *");
double minutes;
minutes = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                              *");
Console.WriteLine("***************************************************************************");
double hours = ds.ConvertMinutesToHours((int)minutes);
Console.WriteLine($"Временной интервал: {minutes} минут = {hours} часов");

Console.ReadKey();